/* Autogenerated by hxtools bin2c */
#ifndef WYOSUPPORT_H
#define WYOSUPPORT_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_wyosupport_jpg[36710];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* WYOSUPPORT_H */
